pbooth-server-master/config/routes.rb
require 'resque/server'

Pbooth::Application.routes.draw do

  root :to => "home#admin"
  get '/home', :to => "home#index"
  get '/admin', :to => "home#admin", as: "admin"
  get '/last_updated', :to => "home#last_updated"
  get '/list', :to => "home#list", as: "list"
  get '/settings', :to => "home#settings", as: "settings"
  get '/branding/:id', :to => "branding#show", as: "branding"

  mount Resque::Server.new, :at => "/resque"

  get "events/settings", to: "events#settings", defaults: { format: 'json' }
  get "events/:id/photos", to: "events#photos", defaults: { format: 'json' }
  resources :events
  post "events/:id/activate", :to => "events#activate", as: "activate_event"
  post "events/:id/deactivate", :to => "events#deactivate", as: "deactivate_event"

  resources :photos
  post 'photos/:id/print', :to => "photos#print"
  post 'photos/:id/share', :to => "photos#share"
  get 'photos/:id/original', to: "photos#show_original"
  get 'photos/:id/zoom', to: "photos#show_branded"
  get 'photos/:id/display', to: "photos#show"

  resources :photosets
  get '/gifs', :to => "home#gifs"
  get 'photosets/:id/zoom', to: "photosets#show_branded"
  get 'photosets/:id/display', to: "photosets#show"
  post 'photosets/:id/print', :to => "photosets#print"
  post 'photosets/:id/share', :to => "photosets#share"

  # Omnmiauth callback url
  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match 'auth/failure', to: redirect('/authentication_failure'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get

  get '/signed_in/:user/done', :to => "home#signed_in", as: "signed_in"
  get '/authentication_failure', :to => "home#authentication_failure", as: "authentication_failure"

  post 'email_gif', to: 'home#send_gif_email'
  #get 'sms', to: 'text_message#twilio'
  #get 'mms', to: 'text_message#mogreet'
  #get 's3', to: 'shares#amazon_s3'
  get 'smugmug', to: 'shares#smugmug'

  post 'twitter', to: 'shares#twitter'
  post 'facebook', to: 'shares#facebook'
  #get 'picasa', to: 'shares#picasa'
end

pbooth-server-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

  protect_from_forgery with: :null_sessions

  def settings
    @event = Event.latest
  end

  def signed_in
  end

  def authentication_failure
  end

  def admin
    SyncEvents.call # Ensure we can see all the events n the directory.
    @events = Event.all
    @event = Event.latest
   
#    if @event == nil
#    	@event = Event.new
#    	@event.id = 0
#	  end
  end

end

pbooth-server-master/app/views/home/admin.html.erb
<div class="latest-event">
	<% puts @event %>
	<% if @event == nil %>
		<p>There are no photos </p>
	<% else %>
		<h2><%= @event.name %> <small>is the latest event. 
		    <%= link_to "Edit", edit_event_path(@event.id) %> | 
		    <%= link_to "Show", event_path(@event.id) %>
		  </small>
		  </h2>
	</div>

	<table>
		<thead>
		  <tr>
		    <th>Event</th>
		    <th>Photos</th>
		    <th>Photosets</th>
		    <th>Select</th>
		    <!--<th>Sync</th>-->
		    <th>Edit | Show</th>
		  </tr>
		</thead>
		<tbody>
		<% @events.each do |event| %>
		  <tr <%= raw 'class="info"' if event.active? %>>
		<td><%= event.name %></td>
		<td><%= event.photos.count %></td>
		<td><%= event.photosets.count %> / <%= event.photosets.fullup_count event.photos_in_set.to_i %> / <%= event.photosets.valid_count %></td>
		<td>
		  <% if event.active? %>
		    <%= form_tag( deactivate_event_path(event.id) ) do -%>
		      <div><%= submit_tag 'Deactivate' %></div>
		    <% end -%>
		  <% else %>
		    <%= form_tag( activate_event_path(event.id) ) do -%>
		      <div><%= submit_tag 'Activate' %></div>
		    <% end -%>
		  <% end %>
		</td>
		  <td>
		    <%= link_to "Edit", edit_event_path(event.id) %> | 
		    <%= link_to "Show", event_path(event.id) %>
		  </td>
	</tr>
	<% end %>
		</tbody>
	</table>

	<div class="bs-callout bs-callout-info">
		    <h4>Tip</h4>
		    <p>Activiating an event will start detecting and processing incoming photos for that event</p>
	</div>
<% end %>

pbooth-server-master/app/views/home/gifs.html.erb
<% @photosets.each do |photoset| %>
  <div class="photo-frame">
    <img src="<%= photoset_path photoset.id %>">
  </div>
<% end %>

pbooth-server-master/app/views/home/index.html.erb
<% @photos.each do |photo| %>
  <div class="photo-frame">
    <img src="<%= photo_path photo.id %>">
  </div>
<% end %>

pbooth-server-master/app/views/home/last_updated.html.erb
<%= @updated %>

pbooth-server-master/app/views/home/last_updated.json.erb
<%= @updated %>

pbooth-server-master/app/views/home/list.html.erb
<p id="notice"><%= notice %></p>


<div class="list">
  
  <div class="item">
    <strong>event:</strong>
    <%= @event.name %>
  </div>

  <div class="item">
    <strong>event_id:</strong>
    <%= @event.id %>
  </div>

  <div class="item">
    <div class="item-header">photos:</div>
    <% @event.photosets.each do |photoset| %>
      <div class="photoset">
        <!-- <h4><%= photoset.id %></h4> -->
        <% photoset.photos.each do |photo| %>
          <div class="photo"><%= photo.id %></div>
        <% end %>
      </div>
  <% end %>
  </div>
</div>

pbooth-server-master/app/views/home/send_gif_email.html.erb
Mail sent