pbooth-server-master/config/routes.rb
require 'resque/server'

Pbooth::Application.routes.draw do

  root :to => "home#admin"
  get '/home', :to => "home#index"
  get '/admin', :to => "home#admin", as: "admin"
  get '/last_updated', :to => "home#last_updated"
  get '/list', :to => "home#list", as: "list"
  get '/settings', :to => "home#settings", as: "settings"
  get '/branding/:id', :to => "branding#show", as: "branding"

  mount Resque::Server.new, :at => "/resque"

  get "events/settings", to: "events#settings", defaults: { format: 'json' }
  get "events/:id/photos", to: "events#photos", defaults: { format: 'json' }
  resources :events
  post "events/:id/activate", :to => "events#activate", as: "activate_event"
  post "events/:id/deactivate", :to => "events#deactivate", as: "deactivate_event"

  resources :photos
  post 'photos/:id/print', :to => "photos#print"
  post 'photos/:id/share', :to => "photos#share"
  get 'photos/:id/original', to: "photos#show_original"
  get 'photos/:id/zoom', to: "photos#show_branded"
  get 'photos/:id/display', to: "photos#show"

  resources :photosets
  get '/gifs', :to => "home#gifs"
  get 'photosets/:id/zoom', to: "photosets#show_branded"
  get 'photosets/:id/display', to: "photosets#show"
  post 'photosets/:id/print', :to => "photosets#print"
  post 'photosets/:id/share', :to => "photosets#share"

  # Omnmiauth callback url
  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match 'auth/failure', to: redirect('/authentication_failure'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get

  get '/signed_in/:user/done', :to => "home#signed_in", as: "signed_in"
  get '/authentication_failure', :to => "home#authentication_failure", as: "authentication_failure"

  post 'email_gif', to: 'home#send_gif_email'
  #get 'sms', to: 'text_message#twilio'
  #get 'mms', to: 'text_message#mogreet'
  #get 's3', to: 'shares#amazon_s3'
  get 'smugmug', to: 'shares#smugmug'

  post 'twitter', to: 'shares#twitter'
  post 'facebook', to: 'shares#facebook'
  #get 'picasa', to: 'shares#picasa'
end

pbooth-server-master/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

pbooth-server-master/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">photoboothPOPup</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <!--
              <li><%= link_to "Home", root_path %></li>
              <li><a href="#photos">Photos</a></li>
              <li><a href="#gifs">Gifs</a></li>
              -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <!--
              <li><%= link_to "Admin", admin_path %></li>
              -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">API<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">HTML</li>
                  <li><%= link_to "/list", list_path %></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">JSON</li>
                  <li><%= link_to "/list", list_path(format: :json) %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>


<!--<nav class="pbooth-nav">
  <div class="click-print-share">
    <div class="cps cps-click"></div>
    <div class="cps cps-print"></div>
    <div class="cps cps-share"></div>
  </div>
</nav>-->

pbooth-server-master/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

pbooth-server-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pbooth" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pbooth" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
      <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>